import { BadRequestException, Injectable } from '@nestjs/common';
import { Role } from '@prisma/client';
import { Resend } from 'resend';
import { createHash, randomInt } from 'crypto';
import { PrismaService } from '../prisma/prisma.service';
import { StorageService } from '../storage/storage.service';
import { AuditService } from '../audit/audit.service';
@Injectable()
export class UsersService { constructor(private prisma:PrismaService,private storage:StorageService,private audit:AuditService){}
private select={id:true,email:true,name:true,role:true,emailConfirmed:true,avatarUrl:true,phone:true,position:true,company:true,location:true,website:true,bio:true,telegramChatId:true,maxUserId:true,webhookUrl:true,twoFactorEnabled:true,createdAt:true,updatedAt:true} as const;
private hashToken(t:string){return createHash('sha256').update(t).digest('hex')}
private normalizeEmail(email:string){return email.trim().toLowerCase()}
private createEmailCode(){return randomInt(100000,1000000).toString()}
private async sendEmailChangeCode(email:string,code:string){const apiKey=process.env.RESEND_API_KEY;if(!apiKey)throw new BadRequestException('Email service is not configured');const resend=new Resend(apiKey);const fromEmail=(process.env.RESEND_FROM?.match(/<([^>]+)>/)?.[1]||process.env.RESEND_FROM||'noreply@incidents64.fun').trim();const result=await resend.emails.send({from:`Цифровой Наблюдатель <${fromEmail}>`,to:email,subject:'Код подтверждения почты',text:`Код подтверждения почты: ${code}. Он действует 15 минут. Если вы не запрашивали смену почты, просто проигнорируйте письмо.`,html:`<div style="margin:0;padding:0;background:#f3f6f8;font-family:Arial,Helvetica,sans-serif;color:#111827"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f3f6f8;padding:28px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:560px;background:#ffffff;border-radius:18px;overflow:hidden;border:1px solid #e5e7eb;box-shadow:0 22px 60px rgba(15,23,42,.12)"><tr><td style="background:#0f172a;padding:24px 28px"><div style="display:inline-block;width:40px;height:40px;border-radius:12px;background:#0f766e;vertical-align:middle;margin-right:12px;text-align:center;line-height:40px;color:#ccfbf1;font-weight:700">ЦН</div><span style="color:#f8fafc;font-size:20px;font-weight:700;vertical-align:middle">Цифровой Наблюдатель</span><div style="color:#cbd5e1;font-size:13px;margin-top:8px">Подтверждение нового адреса почты</div></td></tr><tr><td style="padding:28px"><h1 style="margin:0 0 10px;font-size:22px;line-height:1.25;color:#0f172a">Код подтверждения</h1><p style="margin:0;color:#64748b;font-size:14px;line-height:1.55">Введите этот код в профиле, чтобы завершить смену адреса электронной почты.</p><div style="margin:22px 0;padding:18px;border-radius:14px;background:#f8fafc;border:1px solid #e2e8f0;text-align:center"><div style="font-size:32px;font-weight:800;letter-spacing:8px;color:#0f766e">${code}</div></div><p style="margin:0;color:#64748b;font-size:13px;line-height:1.55">Код действует 15 минут. Если вы не запрашивали смену почты, письмо можно проигнорировать.</p></td></tr></table></td></tr></table></div>`});if(result.error)throw new BadRequestException(`Could not send verification email: ${result.error.message}`)}
findAll(q:any){return this.prisma.user.findMany({where:q.q?{OR:[{email:{contains:q.q,mode:'insensitive'}},{name:{contains:q.q,mode:'insensitive'}}]}:{},select:this.select,take:Number(q.take)||50})}
findOne(id:string){return this.prisma.user.findUniqueOrThrow({where:{id},select:this.select})}
async update(id:string,dto:any,actorId=id){const allowed=['name','phone','position','company','location','website','bio','telegramChatId','maxUserId','webhookUrl'];const data:any={};for(const key of allowed){if(key in dto)data[key]=typeof dto[key]==='string'?dto[key].trim():dto[key] ?? null}const updated=await this.prisma.user.update({where:{id},data,select:this.select});await this.audit.record({userId:actorId,action:'user.profile.updated',entityType:'User',entityId:id,metadata:{fields:Object.keys(data)}});return updated}
async updateRole(actorId:string,id:string,role:Role){const target=await this.prisma.user.findUniqueOrThrow({where:{id},select:{id:true,role:true,email:true}});if(target.role===role)return this.findOne(id);if(target.role==='ADMIN'&&role!=='ADMIN'){const admins=await this.prisma.user.count({where:{role:'ADMIN'}});if(admins<=1)throw new BadRequestException('Cannot remove the last administrator');}const updated=await this.prisma.user.update({where:{id},data:{role},select:this.select});await this.audit.record({userId:actorId,action:'user.role.changed',entityType:'User',entityId:id,metadata:{email:target.email,from:target.role,to:role}});return updated}
async uploadAvatar(id:string,file:any){if(!file)throw new BadRequestException('Avatar file is required');if(!String(file.mimetype||'').startsWith('image/'))throw new BadRequestException('Avatar must be an image');const ext=String(file.mimetype).split('/')[1]?.replace('jpeg','jpg')||'jpg';const avatarUrl=await this.storage.upload(`avatars/${id}-${Date.now()}.${ext}`,file.buffer,file.mimetype,{requireRemote:true});const updated=await this.prisma.user.update({where:{id},data:{avatarUrl},select:this.select});await this.audit.record({userId:id,action:'user.avatar.uploaded',entityType:'User',entityId:id,metadata:{avatarUrl}});return updated}
async requestEmailChange(id:string,emailInput:string){if(!emailInput)throw new BadRequestException('Email is required');const email=this.normalizeEmail(emailInput);const user=await this.prisma.user.findUniqueOrThrow({where:{id},select:{email:true}});if(email===user.email)return {ok:true,message:'Email is already current'};const exists=await this.prisma.user.findFirst({where:{email,NOT:{id}},select:{id:true}});if(exists)throw new BadRequestException('Email already registered');const code=this.createEmailCode();await this.prisma.emailToken.updateMany({where:{email,type:'EMAIL_CHANGE',usedAt:null},data:{usedAt:new Date()}});await this.prisma.emailToken.create({data:{email,tokenHash:this.hashToken(code),type:'EMAIL_CHANGE',expiresAt:new Date(Date.now()+15*60*1000),payload:{userId:id,newEmail:email}}});await this.sendEmailChangeCode(email,code);await this.audit.record({userId:id,action:'user.email_change.requested',entityType:'User',entityId:id,metadata:{newEmail:email}});return {ok:true,message:'Verification code sent'}}
async confirmEmailChange(id:string,emailInput:string,codeInput:string){if(!emailInput||!codeInput)throw new BadRequestException('Email and code are required');const email=this.normalizeEmail(emailInput);const code=String(codeInput).trim();if(!/^\d{6}$/.test(code))throw new BadRequestException('Invalid code');const row=await this.prisma.emailToken.findFirst({where:{email,tokenHash:this.hashToken(code),type:'EMAIL_CHANGE',usedAt:null,expiresAt:{gt:new Date()}},orderBy:{createdAt:'desc'}});const payload=row?.payload as {userId?:string;newEmail?:string}|null;if(!row||payload?.userId!==id||payload?.newEmail!==email)throw new BadRequestException('Invalid code');const exists=await this.prisma.user.findFirst({where:{email,NOT:{id}},select:{id:true}});if(exists)throw new BadRequestException('Email already registered');const updated=await this.prisma.$transaction(async tx=>{await tx.emailToken.update({where:{id:row.id},data:{usedAt:new Date()}});return tx.user.update({where:{id},data:{email,emailConfirmed:true},select:this.select})});await this.audit.record({userId:id,action:'user.email.changed',entityType:'User',entityId:id,metadata:{newEmail:email}});return updated}
loginLogs(id:string){return this.prisma.loginLog.findMany({where:{userId:id},orderBy:{createdAt:'desc'},take:50})}
}
